### ISSUE TITLE
課題クロスサイトリクエストフォージェリ

### ISSUE THREAD

**Issue by fujiiree120** [fujiiree120/lamp_practice#11]
X-Frame-Optionsの設定

- [x] 下記ファイルにheader('X-FRAME-OPTIONS: DENY')を設定する
admin.php
cart.php
index.php
login.php
signup.php

- [x] model/function.phpに ランダムな文字列をもつ$token,セッションにcsrf_tokenを生成する関数  
       get_csrf_token()を作成
- [x] model/function.phpに$tokenとセッション情報のcsrf_tokenを照合する 
       is_valid_csrf_token()を作成

- [x] 下記controllerファイルにis_valid_csrf_token()を実行する処理を追加
       formからhiddenで送信した'csrf_token'を$tokenに格納
admin_insert_item.php
       admin_change_stock.php
       admin_change_status.php
       admin_delete_item.php
       cart_chanhe_amount.php
       cart_delete_cart.php
       finish.php
       index_add_cart.php
       login_process.php
       signup_process.php

- [x] 下記ファイルにget_csrf_token()を実行する処理を追加     　
admin.php
       cart.php
       index.php
       login.php
       signup.php
　　finish.php

- [x] 下記viewファイルのすべてのformタグ内にtype=hidden,name='csrf_token', value=$tokenのinputタグ を作成
admin_view.php
       cart_view.php
       index_view.php
       login_view.php
       signup_view.php

**Comment by thisprodigiousgeek** [comment]
しっかりご理解いただけているようですね！素晴らしい！

* inputタグで取得した'csrf_token' → formからhiddenで送信した'csrf_token'
* 下記ファイルにcsrf_token() →　下記ファイルにget_csrf_token()
* value=$tocken → value=$token

この辺りを修正しておけばIssueはバッチリです。
また、

finish.phpでもget_csrf_token()を実行しないと、 トークンの変更が行われないので気をつけておきましょう！

Issueに上記修正を施した上で、実装に取り掛かっていただいてOKです！

**Comment by fujiiree120** [comment]
iframeサイトの読み込みを禁止する処理を忘れていましたので、追加しました。
ご確認よろしくお願いいたします。

**Comment by thisprodigiousgeek** [comment]
確認遅くなり申し訳ございません！はい、上記のheaderの追加でバッチリです。
なお、header関数については、一切の出力(print, echo)の前に行わなければならないという制限がありますので気をつけてみてくださいね！
そのため、viewファイルで行うよりも、viewをinclude_onceで読み込む直前に行うほうが確実かもしれませんね！
