### ISSUE TITLE
商品の並び替え機能

### ISSUE THREAD

**Issue by fujiiree120** [fujiiree120/lamp_practice#19]
- [ ] index_view.phpに以下のformタグを作成
method = get
action = index.php
name = items_order

- [ ] formタグ内に以下のselect,optionタグを作成
select タグ  id = order_by
option  value = 新着、安い順、高い順

- [ ] プルダウン選択あと送信する jsファイル「submit.js」を作成
   order_by_order.addEventListener()
  第一引数'change'
  第二引数  formタグを送信する関数

- [ ] contoroller/index.phpにformタグのvalueを格納する$order_byを作成

- [ ] model/index.php関数get__items()のSQL文にORDER BYを作成,$order_byの値によって分岐させる
value =  新着順、空白の場合 ORDER BY created DESC
value = 安い順の場合ORDER BY price DESC
value = 高い順の場合ORDER BY price ASC

**Comment by thisprodigiousgeek** [comment]
すみません、こちら見逃しておりました！本日のレッスンで、こちらについてコメントさせていただきますね！22:00-よろしくお願いいたします！
