### ISSUE TITLE
セキュリティ課題：クロスサイトスクリプティング

### ISSUE THREAD

**Issue by fujiiree120** [fujiiree120/lamp_practice#4]
ToDo

・エスケープ処理の関数を追加
- [x] model/functions.phpにエスケープ処理(htmlspecialchars)の関数hを追加する
      →すでにプルリクエスト済み

・htmlタグの消去
- [ ] 関数h内でエスケープ処理した変数$nameにstrip_tags関数でhtmlタグを処理する
      strip_tagsは適用する必要ないので、関数hは修正しなくてよい
　 →strip_tagsを削除し 返り値を修正する
    

・関数の割り当て
- [ ]下記ファイルを"print h($item['name'])"に変更する

対象とするファイル
- [x] admin_view.php
- [x] header_logined.php
- [x] header.php
- [x] messeages.php
- [x] cart.view.php
- [x] finish_view.php
- [x] login_view.php
- [ ] index_view.php
- [ ] signup_view.php

**Comment by fujiiree120** [comment]
html/admin_insert_item.php 29行目
model/function.php　138行目
エスケープ処理の方だけ追加しました。

**Comment by thisprodigiousgeek** [comment]
こちらのIssueを利用して、どのファイルに対して、どのような処理を行うのかをTODOリストとして作成し、その方針で問題ないかレビューを受けるようにしましょう！
まずは方針を十分に書き出した段階で、slackからご一報くださいね！

**Comment by fujiiree120** [comment]
issueの内容を変更しました。
このような書き方でよろしかったでしょうか・

**Comment by thisprodigiousgeek** [comment]
ご連絡ありがとうございます！書き方としてはチェックリストを利用していただいてどのファイルに対してどんな処理をするのか書いているのでバッチリですね！
その上で、方針には問題があるようです。
まず、すでにh関数は最初のプルリクエストで追加されているため、再度追加する必要はありません。
続いて、htmlspecialchars（h関数）でエスケープを行なっていれば、さらにstrip_tagsを適用する必要はありません。
また、エスケープを行うタイミングに問題があります。
エスケープを行うタイミングはいつが望ましいと教科書に書かれているか確認してみましょう！
